# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a937b161d1a286d134d713b1aa3748eda784306efd8b2f80c9c1a404a8fdb142a444cc23323cc615db3c5db1cac3c117b4cacf133799fc5997717e23abfa26e

test:
  secret_key_base: 7420abd9cf7ca71d22e9a706c9845d8008ef71d4b30e13370927e3933ee933919daab6e2f0a8359cf9bbc4fcd583ea5a12c73797d08b361c3838436e5131faca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
